AutoDeployment Password - Setup for user

diff --git a/.github/workflows/autodeploy.yml b/.github/workflows/autodeploy.yml
--- a/.github/workflows/autodeploy.yml
+++ b/.github/workflows/autodeploy.yml
@@ -51,6 +51,9 @@ jobs:
             echo "Building Laravel assets"
             npm run build
 
+            echo "Setting Permissions"
+            sudo chmod -R 777 storage
+
             echo "Installing Next.js dependencies"
             cd ../next-frontend
             npm install
@@ -62,7 +65,7 @@ jobs:
             pm2 restart all || echo "PM2 not found or no processes to restart"
 
             echo "Restarting Queue"
-            sudo -n supervisorctl restart blissful-admin-worker: || echo "Supervisor restart failed"
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S supervisorctl restart blissful-admin-worker || echo "Supervisor restart failed"
 
             echo "✅ Deployment completed successfully!"
           EOF
